#include <iostream> 
using namespace std;
int main()
{
    setlocale(0, "");
    int value1 = 1;
    cout << value1;
    int value2 = 2;
    cout << value2;
    int value3 = 3;
    cout << value3;
    int value4 = 4;
    cout << value4;
    int value5 = 5;
    cout << value5;
    int value6 = 6;
    cout << value6;
    int value7 = 7;
    cout << value7;
    int value8 = 8;
    cout << value8;
    int value9 = 9;
    cout << value9;
    int value10 = 10;
    cout << value10 << endl;

    short num1 = 11;
    cout << num1;
    short num2 = 12;
    cout << num2;
    short num3 = 13;
    cout << num3;
    short num4 = 14;
    cout << num4;
    short num5 = 15;
    cout << num5;
    short num6 = 16;
    cout << num6;
    short num7 = 17;
    cout << num7;
    short num8 = 18;
    cout << num8;
    short num9 = 19;
    cout << num9;
    short num10 = 20;
    cout << num10 << endl;

    long sis1 = 21;
    cout << sis1;
    long sis2 = 22;
    cout << sis2;
    long sis3 = 23;
    cout << sis3;
    long sis4 = 24;
    cout << sis4;
    long sis5 = 25;
    cout << sis5;
    long sis6 = 26;
    cout << sis6;
    long sis7 = 27;
    cout << sis7;
    long sis8 = 28;
    cout << sis8;
    long sis9 = 29;
    cout << sis9;
    long sis10 = 30;
    cout << sis10 << endl;


    float kit1 = 0.1;
    cout << kit1;
    float kit2 = 0.2;
    cout << kit2;
    float kit3 = 0.3;
    cout << kit3;
    float kit4 = 0.4;
    cout << kit4;
    float kit5 = 0.5;
    cout << kit5;
    float kit6 = 0.6;
    cout << kit6;
    float kit7 = 0.7;
    cout << kit7;
    float kit8 = 0.8;
    cout << kit8;
    float kit9 = 0.9;
    cout << kit9;
    float kit10 = 0.32;
    cout << kit10 << endl;

    double lis1 = 0.10;
    cout << lis1;
    double lis2 = 0.11;
    cout << lis2;
    double lis3 = 0.12;
    cout << lis3;
    double lis4 = 0.13;
    cout << lis4;
    double lis5 = 0.14;
    cout << lis5;
    double lis6 = 0.15;
    cout << lis6;
    double lis7 = 0.16;
    cout << lis7;
    double lis8 = 0.17;
    cout << lis8;
    double lis9 = 0.18;
    cout << lis9;
    double lis10 = 0.19;
    cout << lis10 << endl;

    char symbol1 = 'a';
    cout << symbol1;
    char symbol2 = 'b';
    cout << symbol2;
    char symbol3 = 'c';
    cout << symbol3;
    char symbol4 = 'd';
    cout << symbol4;
    char symbol5 = 'e';
    cout << symbol5;
    char symbol6 = 'f';
    cout << symbol6;
    char symbol7 = 'g';
    cout << symbol7;
    char symbol8 = 'i';
    cout << symbol8;
    char symbol9 = 'j';
    cout << symbol9;
    char symbol10 = 'u';
    cout << symbol10 << endl;

    bool gis1 = true;
    cout << gis1;
    bool gis2 = false;
    cout << gis2;
    bool gis3 = true;
    cout << gis3;
    bool gis4 = true;
    cout << gis4;
    bool gis5 = true;
    cout << gis5;
    bool gis6 = true;
    cout << gis6;
    bool gis7 = true;
    cout << gis7;
    bool gis8 = true;
    cout << gis8;
    bool gis9 = true;
    cout << gis9;
    bool gis10 = true;
    cout << gis10 << endl;

    const int oli1 = 101;
    cout << oli1;
    const int oli2 = 102;
    cout << oli2;
    const int oli3 = 103;
    cout << oli3;
    const int oli4 = 104;
    cout << oli4;
    const int oli5 = 105;
    cout << oli5;
    const int oli6 = 106;
    cout << oli6;
    const int oli7 = 107;
    cout << oli7;
    const int oli8 = 108;
    cout << oli8;
    const int oli9 = 109;
    cout << oli9;
    const int oli10 = 110;
    cout << oli10 << endl;

    const short pip1 = 10101;
    cout << pip1;
    const short pip2 = 10202;
    cout << pip2;
    const short pip3 = 10303;
    cout << pip3;
    const short pip4 = 10404;
    cout << pip4;
    const short pip5 = 10505;
    cout << pip5;
    const short pip6 = 10606;
    cout << pip6;
    const short pip7 = 10707;
    cout << pip7;
    const;
} 